name: genotations
channels:
    - conda-forge
    - BjornFJohansson
    - bioconda
    - defaults
dependencies:
    - python=3.10
    - jupyterlab
    - click
    - primer3-py
    - twine
    - pyarrow
    - biopython
    - pip
    - pip:
        - pycomfort
        - polars
        - genomepy
        - git+https://github.com/MrTomRod/DnaFeaturesViewer #to fix bug with biopython 1.8
