name: genotations
channels:
    - conda-forge
    - BjornFJohansson
    - bioconda
    - defaults
dependencies:
    - python=3.10
    - jupyterlab
    - click
    - primer3-py
    - twine
    - pyarrow
    - biopython
    - ucsc-bedtogenepred
    - ucsc-genepredtobed
    - ucsc-genepredtogtf
    - ucsc-gff3togenepred
    - ucsc-gtftogenepred
    - pip
    - pip:
        - pycomfort>=0.0.14
        - polars
        - genomepy
        - loguru
        - git+https://github.com/MrTomRod/DnaFeaturesViewer #to fix bug with biopython 1.8
