name: genotations
channels:
    - conda-forge
    - BjornFJohansson
    - bioconda
    - defaults
dependencies:
    - python=3.10
    - jupyterlab
    - click
    - primer3-py
    - twine
    - dna_features_viewer
    - pyarrow
    - biopython==1.7.9 #temporary, as there is a bug in dna feature viewer
    - pip
    - pip:
        - pycomfort
        - polars
        - genomepy
